/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/coca_cola_azul.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/coca_cola_azul.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={nodes.Cylinder_2.material} />
    </group>
  )
}

useGLTF.preload('/coca_cola_azul.glb')
