/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bolsa_juan_valdez.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bolsa_juan_valdez.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane002.geometry} material={materials.MatteBlack} />
      <mesh geometry={nodes.Plane002_1.geometry} material={materials.Label} />
    </group>
  )
}

useGLTF.preload('/bolsa_juan_valdez.glb')
